### PR TITLE
Select db only if not using the default

### PR DESCRIPTION
**Pull request by simoheinonen**

### CODE REVIEW

**Comment by simoheinonen** [comment]
could also tag a version v0.1.0 after this and use it instead of `dev-master`

**Comment by whatUwant** [comment]
why i still have access to this repo? 😂

**Comment by simoheinonen** [comment]
Hi Bei!!

**Comment by whatUwant** [comment]
Hi Simo

**Comment by rmarchei** [comment]
Bei!! how is it going? this repo is public :D

**Comment by whatUwant** [comment]
oh it's public repo. silly me.
hi ruggero. things are ok-ish.

**Comment by tcz** [comment]
Hi everyone

**Comment by simoheinonen** [comment]
🎆 🌠

**Pull request merged**
